services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - "3333:3306"
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  php:
    container_name: php
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/var/www/html/:consistent
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
    depends_on:
      - db
