config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/.yarn/**",
  "**/*.d.ts",
  "**/assets/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/templates/**",
  "**/testdata/**",
  "**/tests/**",
  "**/vendor/**",
  ".github/**",
  "resources/js/**",
  "bin/**"
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[project]
name = "filament-lockbox"
language = "php"
coverage = true

[coverage]
report = "build/logs/clover.xml"
tool = "phpunit"

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

# --- PHP ONLY PLUGINS ---
[[plugin]]
name = "php-codesniffer"
mode = "comment"

[[plugin]]
name = "phpstan"

[[plugin]]
name = "radarlint-php"
mode = "comment"
